name: Minecraft Paper Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Download Paper
      run: |
        wget https://api.papermc.io/v2/projects/paper/versions/1.20.6/builds/115/downloads/paper-1.20.6-115.jar
        
    - name: Start Minecraft Paper Server
      run: |
        echo "eula=true">eula.txt && java -Xms2G -Xmx4G -jar paper-1.20.6-115.jar &
        
    - name: Start Minecraft Paper Server
      run: |
        sleep 1m

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update Minecraft Paper server
        branch: ${{ github.head_ref }}
