name: Minecraft Paper Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Open Port
      run: |
        sudo iptables -A INPUT -p tcp --dport 25565 -j ACCEPT
        sudo iptables -A FORWARD -p tcp --dport 25565 -j ACCEPT
        sudo iptables -L
        
    - name: Download Paper
      run: |
        wget https://api.papermc.io/v2/projects/paper/versions/1.20.6/builds/115/downloads/paper-1.20.6-115.jar
    - name: Get IP Address
      id: get_ip
      run: |
        echo "::set-output name=ip::$(curl -s https://api.ipify.org)"
        
    - name: Start Minecraft Paper Server
      run: |
        echo "Your Minecraft Paper server is running at ${{ steps.get_ip.outputs.ip }}:25565"
        echo "eula=true">eula.txt
        java -Xms2G -Xmx4G -jar paper-1.20.6-115.jar
     
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update Minecraft Paper server
        branch: ${{ github.head_ref }}
