name: Minecraft Paper Server

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Open Port
      run: |
        sudo iptables -A INPUT -p tcp --dport 25565 -j ACCEPT
        sudo iptables -A FORWARD -p tcp --dport 25565 -j ACCEPT
        sudo iptables -L
        
    - name: Download Paper
      run: |
        wget https://api.papermc.io/v2/projects/paper/versions/1.20.4/builds/497/downloads/paper-1.20.4-497.jar
        
    - name: Setup nodejs
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Start ngrok
      run: |
        npm install -g ngrok
        ngrok config add-authtoken 2BqKKlKfW5O5QAWLoEiiTpiwODn_7yXaqxUNiFvzCRcjfXiCb
        ngrok tcp 25565 &
        sleep 5

    - name: Get ngrok URL
      id: ngrok
      run: |
        curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
        
    - name: Start Minecraft Paper Server
      run: |
        echo "Your Minecraft Paper server is running at $( curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url' )"
        echo "eula=true">eula.txt
        mkdir plugins 
        cd plugins
        wget "https://cdn.modrinth.com/data/NpvuJQoq/versions/QysADh1s/ViaBackwards-4.9.2.jar"
        wget "https://cdn.modrinth.com/data/P1OZGk5p/versions/uuXDjZ6t/ViaVersion-4.9.3.jar"
        cd ..
        timeout 1.5m java -Xms2G -Xmx8G -jar paper-1.20.4-497.jar nogui &
        sleep 120
        
     
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update Minecraft Paper server
        branch: ${{ github.head_ref }}
