name: Minecraft Paper Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Build with Gradle
      run: gradle build
      
    - name: Download Paper
      run: |
        wget https://api.papermc.io/v2/projects/paper/versions/1.19.2/builds/657/downloads/paper-1.19.2-657.jar
        
    - name: Start Minecraft Paper Server
      run: |
        java -Xms2G -Xmx4G -jar paper-1.19.2-657.jar
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
