name: Minecraft Paper Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Open Port
      run: |
        sudo iptables -A INPUT -p tcp --dport 25565 -j ACCEPT
        sudo iptables -A FORWARD -p tcp --dport 25565 -j ACCEPT
        sudo iptables -L
        
    - name: Download Paper
      run: |
        wget https://api.papermc.io/v2/projects/paper/versions/1.20.4/builds/497/download/paper-1.20.4-497.jar
        
    - name: Setup nodejs
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Start ngrok
      run: |
        npm install -g ngrok
        ngrok config add-authtoken 2BqKKlKfW5O5QAWLoEiiTpiwODn_7yXaqxUNiFvzCRcjfXiCb
        ngrok tcp 25565 &
        sleep 5

    - name: Get ngrok URL
      id: ngrok
      run: |
        curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
    - name: Start Minecraft Paper Server
      run: |
        echo "Your Minecraft Paper server is running at ${{ steps.ngrok.outputs.result }}"
        echo "eula=true">eula.txt
        java -Xms2G -Xmx4G -jar paper-1.20.4-497.jar
     
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update Minecraft Paper server
        branch: ${{ github.head_ref }}
